### ISSUE TITLE
Replace IsElement implementation and add dependency to Elemento

### ISSUE THREAD

**Issue by hpehl** [treblereel/crysknife#36]
Currently Crysknife uses its own `IsElement<E extends HTMLElement>` interface. This RFE is about adding a dependency to Elemento and use `org.jboss.elemento.IsElement<E extends HTMLElement>` instead. 

This would improve usability for applications using both Elemento and Crysknife.

**Comment by treblereel** [comment]
Yeap, I like it !

**Comment by hpehl** [comment]
Great I'll prepare a PR.

**Comment by hpehl** [comment]
Fixed by https://github.com/treblereel/crysknife/pull/37
